name: CI/CD Livre d'Or

on:
  push:
    branches: [ "feat-livre-dor" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion au Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: achveiya/mon-backend:latest

      - name: Build et Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: achveiya/mon-frontend:latest