name: Tofu Plan

on:
  pull_request:
    branches: ["main"]
    paths:
      - "2_tds/td5/scripts/tofu/live/lambda-sample/**"
      - ".github/workflows/tofu-plan.yml"

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:
  plan:
    name: "Tofu Plan"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::968196829199:role/lambda-sample-plan
          role-session-name: plan-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.2

      - name: tofu plan
        id: plan
        working-directory: 2_tds/td5/scripts/tofu/live/lambda-sample
        run: |
          tofu init -no-color -input=false
          tofu plan -no-color -input=false

      - uses: peter-evans/create-or-update-comment@v4
        if: always()
        env:
          RESULT_EMOJI: ${{ steps.plan.outcome == 'success' && '✅' || '⚠️' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ${{ env.RESULT_EMOJI }} `tofu plan` output
            ```
            ${{ steps.plan.outputs.stdout }}
            ```
